### ISSUE TITLE
Scrap parts not obscured in hidden section

### ISSUE THREAD

**Issue by musitive** [hiltonjp/journey#82]
![Screen Shot 2020-10-24 at 12 38 35 PM](https://user-images.githubusercontent.com/29413182/97091028-f2d2bc80-15f5-11eb-9da4-9883d815eef6.png)

**Comment by hiltonjp** [comment]
Just needed to update the scrap prefabs' sorting layers:

![image](https://user-images.githubusercontent.com/35467792/97774270-3f515700-1b24-11eb-9e30-50d128bb55f3.png)

**Comment by hiltonjp** [comment]
They used to be on the UI layer, which renders in front of the level's tilemap.
